alter session set "_oracle_script"=true;
drop user DBSOFTBLOOM cascade;

CREATE USER DBSOFTBLOOM
IDENTIFIED BY "@abc123@"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO DBSOFTBLOOM;
GRANT CREATE TABLE TO DBSOFTBLOOM;
GRANT CREATE VIEW TO DBSOFTBLOOM;
GRANT CREATE PROCEDURE TO DBSOFTBLOOM;
GRANT CREATE TRIGGER TO DBSOFTBLOOM;
GRANT CREATE SEQUENCE TO DBSOFTBLOOM;
GRANT CREATE JOB TO DBSOFTBLOOM;
GRANT UNLIMITED TABLESPACE TO DBSOFTBLOOM;





